CREATE TABLE IF NOT EXISTS ai_audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  provider VARCHAR(64) NOT NULL,
  model VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  input_preview TEXT NOT NULL,
  output_preview TEXT NOT NULL,
  request_payload_json LONGTEXT NOT NULL,
  response_payload_json LONGTEXT NOT NULL,
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  error_message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_ai_audit_logs_user_id (user_id),
  KEY idx_ai_audit_logs_conversation_id (conversation_id),
  KEY idx_ai_audit_logs_request_id (request_id),
  KEY idx_ai_audit_logs_provider_model (provider, model),
  KEY idx_ai_audit_logs_status_created_at (status, created_at)
);
