services:
  mysql:
    image: mysql:8.0
    command:
      - --innodb-buffer-pool-size=128M
      - --tmp-table-size=16M
      - --max-heap-table-size=16M
      - --performance-schema=OFF
      - --table-open-cache=128
    ports:
      - "${MYSQL_TEST_PORT:-3310}:3306"

  redis:
    ports:
      - "${REDIS_TEST_PORT:-6380}:6379"

  jaeger:
    ports:
      - "${JAEGER_TEST_PORT:-38686}:16686"
