#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="${RUNTIME_DIR:-$ROOT_DIR/.runtime}"
PID_DIR="$RUNTIME_DIR/pids"
LOG_DIR="$RUNTIME_DIR/logs"
BIN_DIR="$RUNTIME_DIR/bin"
GOCACHE="${GOCACHE:-$RUNTIME_DIR/go-build}"

MYSQL_PORT="${MYSQL_PORT:-3307}"
MYSQL_HOST="${MYSQL_HOST:-127.0.0.1}"
MYSQL_DATABASE="${MYSQL_DATABASE:-chat_workspace_runtime}"
MYSQL_USER="${MYSQL_USER:-chat_app}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-chat_app}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-root}"
MYSQL_DSN="${MYSQL_DSN:-${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}}"

REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_ADDR="${REDIS_ADDR:-${REDIS_HOST}:${REDIS_PORT}}"

AUTH_PORT="${AUTH_PORT:-19081}"
API_PORT="${API_PORT:-19082}"
REALTIME_PORT="${REALTIME_PORT:-19083}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"

RABBITMQ_URL="${RABBITMQ_URL:-redis://${REDIS_ADDR}}"
ELASTICSEARCH_URL="${ELASTICSEARCH_URL:-mock://mysql}"
JWT_SECRET="${JWT_SECRET:-local-dev-secret}"
CORS_ORIGINS="${CORS_ORIGINS:-http://127.0.0.1:${FRONTEND_PORT},http://localhost:${FRONTEND_PORT}}"

MYSQL_DATA_DIR="${MYSQL_DATA_DIR:-$RUNTIME_DIR/mysql-${MYSQL_PORT}}"
MYSQL_SOCKET="$MYSQL_DATA_DIR/mysql.sock"
MYSQL_PID_FILE="$MYSQL_DATA_DIR/mysql.pid"
MYSQL_LOG_FILE="$LOG_DIR/mysql.err"
MYSQL_RUNTIME_MODE="${MYSQL_RUNTIME_MODE:-auto}"
MYSQL_DOCKER_IMAGE="${MYSQL_DOCKER_IMAGE:-mysql:8.4}"
MYSQL_DOCKER_CONTAINER="${MYSQL_DOCKER_CONTAINER:-awesomeproject-mysql-${MYSQL_PORT}}"
MYSQL_DOCKER_STATE_FILE="${MYSQL_DOCKER_STATE_FILE:-$RUNTIME_DIR/mysql-docker.state}"
REDIS_DATA_DIR="${REDIS_DATA_DIR:-$RUNTIME_DIR/redis-${REDIS_PORT}}"
REDIS_PID_FILE="$REDIS_DATA_DIR/redis.pid"
REDIS_LOG_FILE="$LOG_DIR/redis.log"

mkdir -p "$PID_DIR" "$LOG_DIR" "$BIN_DIR" "$MYSQL_DATA_DIR" "$REDIS_DATA_DIR"

export ROOT_DIR RUNTIME_DIR PID_DIR LOG_DIR BIN_DIR
export GOCACHE
export MYSQL_PORT MYSQL_HOST MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD MYSQL_ROOT_PASSWORD MYSQL_DSN
export MYSQL_RUNTIME_MODE MYSQL_DOCKER_IMAGE MYSQL_DOCKER_CONTAINER MYSQL_DOCKER_STATE_FILE
export REDIS_HOST REDIS_PORT REDIS_ADDR
export AUTH_PORT API_PORT REALTIME_PORT FRONTEND_PORT
export RABBITMQ_URL ELASTICSEARCH_URL JWT_SECRET CORS_ORIGINS
export MYSQL_DATA_DIR MYSQL_SOCKET MYSQL_PID_FILE MYSQL_LOG_FILE REDIS_DATA_DIR REDIS_PID_FILE REDIS_LOG_FILE
